pipeline {
  agent any
  triggers {
    pollSCM '*/5 * * * *'
  }

  stages {
    stage ("CICD"){
      steps {
        sh '''
          echo "Hello World!"
          pwd
          ls -al
          whoami
        '''
        ansiblePlaybook(
          playbook: 'devops/maven-ansible-playbook.yaml', 
          credentialsId: 'tinakaa',
          disableHostKeyChecking: true,
        )
      }
    }
    stage ("Build"){
      steps {
       sh '''
        echo "stage Build, hello"
        pwd
        whoami
       '''  
      }
    }
  }
}
