pipeline {
  agent any
  triggers {
    pollSCM '*/5 * * * *'
  }

  stages {
    stage ("Tomcat"){
      steps {
        sh '''
          echo "Hello World!"
          pwd
          ls -al
          whoami
        '''
        ansiblePlaybook(
          playbook: 'devops/maven-ansible-playbook.yaml', 
          credentialsId: 'tinakaa',
          disableHostKeyChecking: true,
        )
      }
    }
    stage ("Compile"){
      steps {
       sh '''
        echo "stage Compile, to Compile src code from Jenkins workspace"
        pwd
        whoami
       '''
       //deploy adapters: [tomcat8(credentialsId: 'tomcat', path: '/opt/app/target', url: 'http://192.168.127.130:8080/')], contextPath: 'tinademo', war: 'AnsibleJenkinsProject-0.0.1-SNAPSHOT.war'
      }
    }
    stage ("Package"){
      steps {
       sh '''
        echo "stage package, to pacakge src code form Jenkins workspace."
       '''
      }
    }
    stage ("Deploy"){
      steps {
       sh '''
        echo "stage Deploy, to Deploy war file from jenkins workspace to tomcat machine"
       '''
      }
    }
  }
}
